<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/6/7 0007
 * Time: 下午 4:47
 */

namespace backend\controllers;


use backend\models\AuthItem;
use Yii;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

class AdminBaseController extends Controller
{
	public $pathInfo;
	
	/**
	 * @throws ForbiddenHttpException
	 * @throws \yii\base\InvalidConfigException
	 * @throws NotFoundHttpException
	 */
	public function init()
	{
		$this->pathInfo =Yii::$app->request->getPathInfo();
		if(!Yii::$app->user->can($this->pathInfo)){
			$item = AuthItem::findOne(['name'=>$this->pathInfo]);
			$msg = @$item->description ? "尚无{$item->description}权限" : '此功能不存在或未授访问权限';
			throw new ForbiddenHttpException($msg);
		}
		parent::init(); // TODO: Change the autogenerated stub
	}
}