<?php

namespace console\controllers;

use backend\config\AuthConfig;
use backend\models\AuthAssignment;
use backend\models\AuthItem;
use Yii;
use yii\base\Exception;
use yii\console\Controller;
use yii\rbac\Item;
use yii\rbac\ManagerInterface;

class RbacController extends Controller
{
	private $auth;
	private $handle;
	private $msg;
	private $role;
	
	public function init()
	{
		$this->auth = AuthConfig::getAuth();
		$this->handle = AuthConfig::getHandle();
		$this->role = AuthConfig::getRole();
		parent::init(); // TODO: Change the autogenerated stub
	}
	
	/**
	 * @throws \Exception
	 */
	public function actionInit()
	{
		$amg = Yii::$app->authManager;
		
		$this->_addPermission($amg);
		$this->_addRole($amg);
		$this->_addAssignment($amg);

//        // 添加 "createPost" 权限
//        $createPost = $auth->createPermission('createPost');
//        $createPost->description = '新增文章';
//        $auth->add($createPost);
//
//        // 添加 "updatePost" 权限
//        $updatePost = $auth->createPermission('updatePost');
//        $updatePost->description = '修改文章';
//        $auth->add($updatePost);
//
//        // 添加 "deletePost" 权限
//        $deletePost = $auth->createPermission('deletePost');
//        $deletePost->description = '删除文章';
//        $auth->add($deletePost);
//
//        // 添加 "approveComment" 权限
//        $approveComment = $auth->createPermission('approveComment');
//        $approveComment->description = '审核评论';
//        $auth->add($approveComment);
//
//
//        // 添加 "postadmin" 角色并赋予 "updatePost" “deletePost” “createPost”
//        $postAdmin = $auth->createRole('postAdmin');
//        $postAdmin->description = '文章管理员';
//        $auth->add($postAdmin);
//        $auth->addChild($postAdmin, $updatePost);
//        $auth->addChild($postAdmin, $createPost);
//        $auth->addChild($postAdmin, $deletePost);
//
//        // 添加 "postOperator" 角色并赋予  “deletePost”
//        $postOperator = $auth->createRole('postOperator');
//        $postOperator->description = '文章操作员';
//        $auth->add($postOperator);
//        $auth->addChild($postOperator, $deletePost);
//
//        // 添加 "commentAuditor" 角色并赋予  “approveComment”
//        $commentAuditor = $auth->createRole('commentAuditor');
//        $commentAuditor->description = '评论审核员';
//        $auth->add($commentAuditor);
//        $auth->addChild($commentAuditor, $approveComment);
//
//        // 添加 "admin" 角色并赋予所有其他角色拥有的权限
//        $admin = $auth->createRole('admin');
//        $commentAuditor->description = '系统管理员';
//        $auth->add($admin);
//        $auth->addChild($admin, $postAdmin);
//        $auth->addChild($admin, $commentAuditor);
//
//
//
//        // 为用户指派角色。其中 1 和 2 是由 IdentityInterface::getId() 返回的id （译者注：user表的id）
//        // 通常在你的 User 模型中实现这个函数。
//        $auth->assign($admin, 1);
//        $auth->assign($postAdmin, 2);
//        $auth->assign($postOperator, 3);
//        $auth->assign($commentAuditor, 4);
	}
	
	private function _addPermission(ManagerInterface $amg)
	{
		$error = $succ = 0;
		//1、清空所有的权限
		AuthItem::deleteAll(['type' => Item::TYPE_PERMISSION]);
		//循环配置文件，逐一添加需要的权限
		foreach ($this->auth as $auth => $item) {
			$auth_desc = $item['desc'];
			$this->handle = array_merge($this->handle,$item['extraHandle']);
			foreach ($this->handle as $handle => $desc) {
				$auth_handle = $auth . '/' . $handle;
				$p = $amg->createPermission($auth_handle);
				$p->description = $auth_desc . $desc;
				$amg->add($p);
				$this->msg = "add permission [{$auth_handle}] success !";
				$succ++;
				$this->outputInfo();
			}
		}
		$this->msg = "add permission success count : [{$succ}]";
		$this->outputInfo();
	}
	
	private function _addRole(ManagerInterface $amg)
	{
		$succ = 0;
		//1、清空所有的角色
		AuthItem::deleteAll(['type' => Item::TYPE_ROLE]);
		//循环配置文件，逐一添加需要的角色
		foreach ($this->role as $name => $info) {
			$desc = $info['desc'];
			$parent = $info['parent'];
			$role = $amg->createRole($name);
			$role->description = $desc;
			$amg->add($role);
			/**
			 * 是否添加层级关系
			 */
			if($parent){
				$parent_role = $amg->getRole($parent);
				try {
					$amg->addChild($parent_role, $role);
				} catch (Exception $e) {
					$this->msg = 'parent has been added';
					$this->outputInfo();
				}
				$this->msg = "add {$parent_role->name}'s child [$name] success !";
				$this->outputInfo();
			}
			$this->msg = "add role [{$name}] success !";
			$succ++;
			$this->outputInfo();
		}
		$this->msg = "add role success count : [{$succ}]";
		$this->outputInfo();
	}
	
	public function outputInfo()
	{
		print_r("{$this->msg}\n");
	}
	
	/**
	 * 初始化adminUser的第一个用户为超级管理员
	 * @param ManagerInterface $amg
	 * @return bool
	 * @throws \Exception
	 */
	private function _addAssignment(ManagerInterface $amg)
	{
		$succ = $error = 0;
		$super_admin_id = AuthConfig::getSuperAdminId();
		if(empty($super_admin_id)){
			$this->msg = "there is no admin user in system !";
			$this->outputInfo();
			return false;
		}
		$super_role = $amg->getRole(AuthConfig::SUPER_ADMIN);
		$per = $amg->getPermissions();
		
		//给第一个用户添加超管角色
		$one = AuthAssignment::findOne(['item_name'=>AuthConfig::SUPER_ADMIN]);
		if($one){
			$this->msg = 'SuperAdmin has been set !';
			$this->outputInfo();
		}else{
			$r_assign = $amg->assign($super_role,$super_admin_id);
			$this->msg = $r_assign ? "set admin_user_id [{$super_admin_id}] as SuperAdmin} success !" : "set admin_user_id [{$super_admin_id}] as SuperAdmin} error !";
			$this->outputInfo();
		}
		
		
		//给超管角色分配所有权限
		foreach ($per as $item) {
			$r = $amg->addChild($super_role,$item);
			$r ? $succ++ : $error++;
		}
		$this->msg = "Set all permissions for super administrators success count : [{$succ}]";
		$this->outputInfo();
		$this->msg = "Set all permissions for super administrators error count : [{$error}]";
		$this->outputInfo();
	}
	
}